export { default as Avatar } from './avatar.png';
export { default as BackArrow } from './back-arrow.png';
export { default as Close } from './close.png';
export { default as Cubes } from './cubes.png';
export { default as CubesInactive } from './cubes-inactive.png';
export { default as Home } from './home.png';
export { default as HomeInactive } from './home-inactive.png';
export { default as InfoCircle } from './info-circle.png';
export { default as InfoCircleInactive } from './info-circle-inactive.png';
